services:
  modelship-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./mlflow:/mlflow
      - ./pyproject.toml:/app/pyproject.toml
    environment:
      - PYTHONPATH=/app
      - MLFLOW_TRACKING_URI=sqlite:////mlflow/mlflow.db

  modelship-mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5001:5000"
    volumes:
      - ./mlflow:/mlflow
    command:  mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:////mlflow/mlflow.db --default-artifact-root /mlflow/artifacts --serve-artifacts
